apiVersion: apps/v1
kind: Deployment
metadata:
  name: videomanagementservice
spec:
  replicas: 1
  selector:
      matchLabels:
          app: videomanagementservice
  template:
    metadata:
      labels:
        app: videomanagementservice
    spec:
      containers:
      - name: videomanagementservice
        image: videomanagementservice:v1
        volumeMounts:
            - mountPath: /storage
              name: storage-path 
        ports:
          - containerPort: 8080
        imagePullPolicy: Never
        env:
        - name: MONGO_ROOT_USERNAME
          value: admin
        - name: MONGO_ROOT_PASSWORD
          value: admin
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_PORT
          value: '27017'
        - name: MONGO_DBNAME
          value: video-server
        - name: KAFKA_ADDRESS
          value: kafkaa:9092
        - name: KAFKA_GROUP_ID
          value: vms-group
        - name: KAFKA_MAIN_TOPIC
          value: main-topic
      volumes:
        - name: storage-path
          hostPath: 
            path: /home/Storage
            type: DirectoryOrCreate




