apiVersion: apps/v1
kind: Deployment
metadata:
  name: spout
spec:
  replicas: 1
  selector:
      matchLabels:
          app: spout
  template:
    metadata:
      labels:
        app: spout
    spec:
      containers:
      - name: spout
        image: spout:v1
        volumeMounts:
            - mountPath: /logs
              name: logs-path    
        ports:
          - containerPort: 8083
        imagePullPolicy: Never
        env:
        - name: KAFKA_ADDRESS
          value: kafkaa:9092
        - name: KAFKA_GROUP_ID
          value: spout-group
        - name: KAFKA_METRICS_TOPIC
          value: metrics-topic
      volumes:
        - name: logs-path
          hostPath: 
            path: /home/data/stats
            type: DirectoryOrCreate




