FROM maven:3-jdk-8 as builder
WORKDIR /app
COPY . .
RUN mvn package -P production




FROM java:8
WORKDIR /app
RUN echo "deb [check-valid-until=no] http://cdn-fastly.deb.debian.org/debian jessie main" > /etc/apt/sources.list.d/jessie.list
RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
RUN sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
RUN apt-get -o Acquire::Check-Valid-Until=false update
RUN apt-get install -y ffmpeg
ADD ./target/videoprocessingservice-0.0.1-SNAPSHOT.jar ./service.jar
CMD java -jar service.jar
